In [3]:
import pandas as pd
import numpy as np

In [4]:
from numpy.random import randn

In [6]:
df = pd.DataFrame(randn(5, 4), index=['A', 'B', 'C', 'D', 'E'], columns='W X Y Z'.split())
df

          W         X         Y         Z
A  0.556868  1.338454  0.242946 -0.774154
B -0.666038 -1.883245  0.179562  1.030169
C -0.437163  1.274623 -0.975194  1.432736
D -1.276206 -0.179626  1.794092 -0.072935
E -0.173002  0.814258  0.372984  0.696560

In [7]:
df['W']

A    0.556868
B   -0.666038
C   -0.437163
D   -1.276206
E   -0.173002
Name: W, dtype: float64

In [8]:
df[['W']]

          W
A  0.556868
B -0.666038
C -0.437163
D -1.276206
E -0.173002

In [10]:
df['new'] = df['W']
df

          W         X         Y         Z       new
A  0.556868  1.338454  0.242946 -0.774154  0.556868
B -0.666038 -1.883245  0.179562  1.030169 -0.666038
C -0.437163  1.274623 -0.975194  1.432736 -0.437163
D -1.276206 -0.179626  1.794092 -0.072935 -1.276206
E -0.173002  0.814258  0.372984  0.696560 -0.173002

In [11]:
df['new'] = df['W'] + df['Y']
df

          W         X         Y         Z       new
A  0.556868  1.338454  0.242946 -0.774154  0.799814
B -0.666038 -1.883245  0.179562  1.030169 -0.486477
C -0.437163  1.274623 -0.975194  1.432736 -1.412357
D -1.276206 -0.179626  1.794092 -0.072935  0.517886
E -0.173002  0.814258  0.372984  0.696560  0.199982

In [12]:
df.drop('new', axis=1)

          W         X         Y         Z
A  0.556868  1.338454  0.242946 -0.774154
B -0.666038 -1.883245  0.179562  1.030169
C -0.437163  1.274623 -0.975194  1.432736
D -1.276206 -0.179626  1.794092 -0.072935
E -0.173002  0.814258  0.372984  0.696560

In [13]:
df.drop('new', axis=1, inplace=True)

In [15]:
df.loc['A']

W    0.556868
X    1.338454
Y    0.242946
Z   -0.774154
Name: A, dtype: float64

In [17]:
df.iloc[0, 2]

np.float64(0.24294560273339133)