In [2]:
import pandas as pd
import numpy as np

In [3]:
from numpy.random import randn

In [4]:
df = pd.DataFrame(randn(5, 4), index=['A', 'B', 'C', 'D', 'E'], columns='W X Y Z'.split())
df

          W         X         Y         Z
A -1.627650  1.130697 -0.583013  1.390130
B -0.270883  0.972154 -0.701757 -0.180562
C -1.159295 -0.624430  0.142351 -0.283770
D -0.129060 -0.812981 -0.272772  0.345361
E  0.747882  0.551424  0.026031 -0.899096

In [5]:
df.loc[['A', 'B'], ['W']]

          W
A -1.627650
B -0.270883

In [7]:
df.iloc[:-1,1:3]

          X         Y
A  1.130697 -0.583013
B  0.972154 -0.701757
C -0.624430  0.142351
D -0.812981 -0.272772

In [10]:

df[df['Y'] > 0] # retorna o dataframe quando as celula da coluna Y for maior que zero

          W         X         Y         Z
C -1.159295 -0.624430  0.142351 -0.283770
E  0.747882  0.551424  0.026031 -0.899096

In [11]:
df[(df['Y'] > 0) & (df['W'] > 0)]

          W         X         Y         Z
E  0.747882  0.551424  0.026031 -0.899096