In [1]:
import pandas as pd
import numpy as np
from numpy.random import randn
df = pd.DataFrame(randn(5, 4), index=['A', 'B', 'C', 'D', 'E'], columns='W X Y Z'.split())
df

          W         X         Y         Z
A  2.401690 -0.813873  0.567920 -1.472886
B  0.666134  0.333604  0.354742 -0.987716
C  1.484144  1.254354 -0.350704  1.600950
D -0.392427  1.379056  0.942567  0.438641
E -0.731774 -0.148036 -1.098294 -2.066448

In [2]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(outside, inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [4]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [5]:
df = pd.DataFrame(np.random.randn(6,2), index=hier_index, columns=['A', 'B'])
df

             A         B
G1 1 -1.060715  0.873974
   2  0.105573 -0.048520
   3  0.088951  0.443920
G2 1  0.043584  0.374170
   2  0.733134 -0.899014
   3 -1.833795 -1.002362

In [6]:
df.loc['G1'].loc[1]

A   -1.060715
B    0.873974
Name: 1, dtype: float64

In [7]:
df.index.names = ['Grupo', 'Número']

In [8]:
df

                     A         B
Grupo Número
G1    1      -1.060715  0.873974
      2       0.105573 -0.048520
      3       0.088951  0.443920
G2    1       0.043584  0.374170
      2       0.733134 -0.899014
      3      -1.833795 -1.002362