In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({
    'A': [1, 2, np.nan],
    'B': [5, np.nan, np.nan],
    'C': [1, 2, 3]
})

In [4]:
df.dropna(axis=0)

     A    B  C
0  1.0  5.0  1

In [5]:
df.dropna(axis=1, thresh=2)

     A  C
0  1.0  1
1  2.0  2
2  NaN  3