In [19]:
import pandas as pd
# Cria um DataFrame
data = {'Classe':['Júnior','Júnior','Pleno','Pleno','Sênior','Sênior'],
       'Nome':['Jorge','Carlos','Roberta','Patrícia','Bruno','Vera'],
       'Venda':[200,120,340,124,243,350]}

In [20]:
df = pd.DataFrame(data)

In [21]:
grup = df.groupby('Classe')

In [22]:
grup.sum()

                   Nome  Venda
Classe
Júnior      JorgeCarlos    320
Pleno   RobertaPatrícia    464
Sênior        BrunoVera    593

In [15]:
df2 = df.copy()

In [ ]:
df2['Venda'] = [150, 432, 190, 230, 410, 155]

In [23]:
df

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350

In [14]:
df2

   Classe      Nome  Venda
0  Júnior     Jorge    200
1  Júnior    Carlos    120
2   Pleno   Roberta    340
3   Pleno  Patrícia    124
4  Sênior     Bruno    243
5  Sênior      Vera    350

In [24]:
df2.groupby(['Classe', 'Nome']).sum()

                 Venda
Classe Nome
Júnior Carlos      120
       Jorge       200
Pleno  Patrícia    124
       Roberta     340
Sênior Bruno       243
       Vera        350